### ISSUE TITLE
deprecated API.

### ISSUE THREAD

**Issue by karenYerevan** [wix/react-native-swipe-view#5]
E:\forbuild\node_modules\react-native-swipe-view\android\src\main\java\com\wix\RNSwipeView\SwipeViewPackage.java:22: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: E:\forbuild\node_modules\react-native-swipe-view\android\src\main\java\com\wix\RNSwipeView\SwipeView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:RNSwipeView:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':RNSwipeView:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by tokland** [comment]
Found this problem with react-native 0.50.4. I simply removed that deprecated method `createJSModules` and it seems to work fine. https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactPackage.java

**Comment by ldco2016** [comment]
I am getting this error when upgrading from RN 0.53.3 to 0.57.8:

`Execution failed for task ':RNSwipeView:processDebugAndroidTestResources'`

```
/Users/danale/Projects/engage-application.mobile/node_modules/react-native-swipe-view/android/build/intermediates/incremental/mergeDebugAndroidTestResources/merged.dir/values/values.xml:226: error: resource android:attr/fontStyle not found.
/Users/danale/Projects/engage-application.mobile/node_modules/react-native-swipe-view/android/build/intermediates/incremental/mergeDebugAndroidTestResources/merged.dir/values/values.xml:226: error: resource android:attr/font not found.
/Users/danale/Projects/engage-application.mobile/node_modules/react-native-swipe-view/android/build/intermediates/incremental/mergeDebugAndroidTestResources/merged.dir/values/values.xml:226: error: resource android:attr/fontWeight not found.
error: failed linking references.
```

I am using `"react-native-swipe-view": "https://github.com/jjd314/react-native-swipe-view",` in my `package.json` file.

How do I fix this?
